project/stocks/__init__.py
"""
The stocks blueprint handles the user management for this application.
Specifically, this blueprint allows for users to add, edit, and delete
stock data from their portfolio.
"""
from flask import Blueprint

stocks_blueprint = Blueprint('stocks', __name__, template_folder='templates')

from . import routes

project/stocks/routes.py
from . import stocks_blueprint
from flask import current_app, render_template, request, flash, redirect, url_for, abort
from pydantic import BaseModel, validator, ValidationError
from project.models import Stock
from project import database
# import click
from flask_login import login_required, current_user
from datetime import datetime


# --------------
# Helper Classes
# --------------

class StockModel(BaseModel):
    """Class for parsing new stock data from a form."""
    stock_symbol: str
    number_of_shares: int
    purchase_price: float

    @validator('stock_symbol')
    def stock_symbol_check(cls, value):
        if not value.isalpha() or len(value) > 5:
            raise ValueError('Stock symbol must be 1-5 characters')
        return value.upper()


# -----------------
# Request Callbacks
# -----------------

# Request callback functions were provided as an example, but are now commented
# out to avoid unnecessary logging.
#
# @stocks_blueprint.before_request
# def stocks_before_request():
#     current_app.logger.info('Calling before_request() for the stocks blueprint...')
#
#
# @stocks_blueprint.after_request
# def stocks_after_request(response):
#     current_app.logger.info('Calling after_request() for the stocks blueprint...')
#     return response
#
#
# @stocks_blueprint.teardown_request
# def stocks_teardown_request(error=None):
#     current_app.logger.info('Calling teardown_request() for the stocks blueprint...')


# ------------
# CLI Commands
# ------------

# CLI commands were provided as an example of how to create CLI commands,
# but they do not work after further updates to the `Stock` model.
#
# @stocks_blueprint.cli.command('create_default_set')
# def create_default_set():
#     """Create three new stocks and add them to the database"""
#     stock1 = Stock('HD', '25', '247.29')
#     stock2 = Stock('TWTR', '230', '31.89')
#     stock3 = Stock('DIS', '65', '118.77')
#     database.session.add(stock1)
#     database.session.add(stock2)
#     database.session.add(stock3)
#     database.session.commit()
#
#
# @stocks_blueprint.cli.command('create')
# @click.argument('symbol')
# @click.argument('number_of_shares')
# @click.argument('purchase_price')
# def create(symbol, number_of_shares, purchase_price):
#     """Create a new stock and add it to the database"""
#     stock = Stock(symbol, number_of_shares, purchase_price)
#     database.session.add(stock)
#     database.session.commit()


# ------
# Routes
# ------

@stocks_blueprint.route('/')
def index():
    current_app.logger.info('Calling the index() function.')
    return render_template('stocks/index.html')


@stocks_blueprint.route('/add_stock', methods=['GET', 'POST'])
@login_required
def add_stock():
    if request.method == 'POST':
        try:
            stock_data = StockModel(
                stock_symbol=request.form['stock_symbol'],
                number_of_shares=request.form['number_of_shares'],
                purchase_price=request.form['purchase_price']
            )
            print(stock_data)

            # Save the form data to the database
            new_stock = Stock(stock_data.stock_symbol,
                              stock_data.number_of_shares,
                              stock_data.purchase_price,
                              current_user.id,
                              datetime.fromisoformat(request.form['purchase_date']))
            database.session.add(new_stock)
            database.session.commit()

            flash(f"Added new stock ({stock_data.stock_symbol})!", 'success')
            current_app.logger.info(f"Added new stock ({request.form['stock_symbol']})!")
            return redirect(url_for('stocks.list_stocks'))
        except ValidationError as e:
            print(e)

    return render_template('stocks/add_stock.html')


@stocks_blueprint.route('/stocks')
@login_required
def list_stocks():
    stocks = Stock.query.order_by(Stock.id).filter_by(user_id=current_user.id).all()

    current_account_value = 0.0
    for stock in stocks:
        stock.get_stock_data()
        database.session.add(stock)
        current_account_value += stock.get_stock_position_value()

    database.session.commit()
    return render_template('stocks/stocks.html', stocks=stocks, value=round(current_account_value, 2))


@stocks_blueprint.route("/chartjs_demo1")
def chartjs_demo1():
    return render_template('stocks/chartjs_demo1.html')


@stocks_blueprint.route("/chartjs_demo2")
def chartjs_demo2():
    title = 'Monthly Data'
    labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August']
    values = [10.3, 9.2, 8.7, 7.1, 6.0, 4.4, 7.6, 8.9]
    return render_template('stocks/chartjs_demo2.html', values=values, labels=labels, title=title)


@stocks_blueprint.route("/chartjs_demo3")
def chartjs_demo3():
    title = 'Daily Prices'
    labels = [datetime(2020, 2, 10),   # Monday 2/10/2020
              datetime(2020, 2, 11),   # Tuesday 2/11/2020
              datetime(2020, 2, 12),   # Wednesday 2/12/2020
              datetime(2020, 2, 13),   # Thursday 2/13/2020
              datetime(2020, 2, 14),   # Friday 2/14/2020
              datetime(2020, 2, 17),   # Monday 2/17/2020
              datetime(2020, 2, 18),   # Tuesday 2/18/2020
              datetime(2020, 2, 19)]   # Wednesday 2/19/2020
    values = [10.3, 9.2, 8.7, 7.1, 6.0, 4.4, 7.6, 8.9]
    return render_template('stocks/chartjs_demo3.html', values=values, labels=labels, title=title)


@stocks_blueprint.route('/stocks/<id>')
@login_required
def stock_details(id):
    stock = Stock.query.filter_by(id=id).first_or_404()

    if stock.user_id != current_user.id:
        abort(403)

    title, labels, values = stock.get_weekly_stock_data()
    return render_template('stocks/stock_details.html', stock=stock, title=title, labels=labels, values=values)


@stocks_blueprint.route('/stocks/<id>/delete')
@login_required
def delete_stock(id):
    stock = Stock.query.filter_by(id=id).first_or_404()

    if stock.user_id != current_user.id:
        abort(403)

    database.session.delete(stock)
    database.session.commit()
    flash(f'Stock ({stock.stock_symbol}) was deleted!', 'success')
    current_app.logger.info(f'Stock ({stock.stock_symbol}) was deleted for user: {current_user.id}!')
    return redirect(url_for('stocks.list_stocks'))


@stocks_blueprint.route('/stocks/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_stock(id):
    stock = Stock.query.filter_by(id=id).first_or_404()

    if stock.user_id != current_user.id:
        abort(403)

    if request.method == 'POST':
        # Edit the stock data in the database
        stock.update(request.form['number_of_shares'],
                     request.form['purchase_price'],
                     datetime.fromisoformat(request.form['purchase_date']))
        database.session.add(stock)
        database.session.commit()

        flash(f'Stock ({ stock.stock_symbol }) was updated!', 'success')
        current_app.logger.info(f'Stock ({ stock.stock_symbol }) was updated by user: { current_user.id}')
        return redirect(url_for('stocks.list_stocks'))

    return render_template('stocks/edit_stock.html', stock=stock)

project/stocks/templates/stocks/add_stock.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form_style.css') }}">
{% endblock %}

{% block content %}
<div class="form-wrap">
  <h1>Add a Stock:</h1>

  <form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    <div class="field">
      <label for="stockSymbol">Stock Symbol <em>(required)</em></label>
      <input type="text" id="stockSymbol" name="stock_symbol" required pattern="[A-Z]{1,5}" />
    </div>

    <div class="field">
      <label for="numberOfShares">Number of Shares <em>(required)</em></label>
      <input type="text" id="numberOfShares" name="number_of_shares" required />
    </div>

    <div class="field">
      <label for="purchasePrice">Purchase Price ($) <em>(required)</em></label>
      <input
        type="text"
        id="purchasePrice"
        name="purchase_price"
        placeholder="$300.00"
        required />
    </div>

    <div class="field">
      <label for="purchaseDate">Purchase Date <em>(required)</em></label>
      <input type="date" id="purchaseDate" name="purchase_date"  placeholder="YYYY-MM-DD" required>
    </div>

    <div class="field">
      <button type="submit">Submit</button>
    </div>
  </form>
</div>
{% endblock %}

project/stocks/templates/stocks/chartjs_demo1.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block content %}
<h2>Chart.js Demo #1</h2>
<br>
<canvas id="stockChart" width="500" height="400"></canvas>
{% endblock %}

{% block javascript %}
<script>
// Get the canvas element for modifying the data contents
var ctx = document.getElementById('stockChart').getContext('2d');

// Set the default font color for each chart
Chart.defaults.global.defaultFontColor = 'black';

// Create a new line chart
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    datasets: [{
      label: 'Count',
      data: [12, 19, 3, 5, 2, 3],
      backgroundColor: 'blue',
      borderColor: 'white',
      borderWidth: 1,
    }]
  },
});
</script>
{% endblock %}

project/stocks/templates/stocks/chartjs_demo2.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block content %}
<h2>ChartJS Demo #2</h2>
<br>
<canvas id="stockChart" width="500" height="400"></canvas>
{% endblock %}

{% block javascript %}
<script>
// Get the canvas element for modifying the data contents
var ctx = document.getElementById('stockChart').getContext('2d');

// Set the default font color for each chart
Chart.defaults.global.defaultFontColor = 'black';

// Create a new line chart
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels:
      [{% for item in labels %}
        "{{item}}",
      {% endfor %}],
    datasets: [{
      label: 'Price ($)',
      data:
        [{% for item in values %}
          {{item}},
        {% endfor %}],
      backgroundColor: 'blue',
      borderColor: 'white',
      borderWidth: 1
    }]
  },
  options: {
    title: {
      display: true,
      text: "{{ title }}"
    },
    legend: {
      display: true,
      position: 'bottom',
      align: 'center'
    },
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        },
      }],
    }
  }
});
</script>
{% endblock %}

project/stocks/templates/stocks/chartjs_demo3.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block content %}
<h2>ChartJS Demo #3</h2>
<br>
<canvas id="stockChart" width="500" height="400"></canvas>
{% endblock %}

{% block javascript %}
<script>
// Get the canvas element for modifying the data contents
var ctx = document.getElementById('stockChart').getContext('2d');

// Set the default font color for each chart
Chart.defaults.global.defaultFontColor = 'black';

// Create a new line chart
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels:
      [{% for item in labels %}
         "{{item.strftime("%m/%d/%Y")}}",
      {% endfor %}],
      datasets: [{
      label: 'Price ($)',
      data:
        [{% for item in values %}
          {{item}},
        {% endfor %}],
      backgroundColor: 'blue',
      borderColor: 'white',
      borderWidth: 1
    }]
  },
  options: {
    title: {
      display: true,
      text: "{{ title }}"
    },
    legend: {
      display: true,
      position: 'bottom',
      align: 'center'
    },
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        },
      }],
    }
  }
});
</script>
{% endblock %}

project/stocks/templates/stocks/edit_stock.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form_style.css') }}">
{% endblock %}

{% block content %}
<div class="form-wrap">
  <h1>Edit Stock ({{ stock.stock_symbol }}):</h1>

  <form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    <div class="field">
      <label for="numberOfShares">Number of Shares</label>
      <input
        type="text"
        id="numberOfShares"
        name="number_of_shares"
        placeholder="{{ stock.number_of_shares }}" />
    </div>

    <div class="field">
      <label for="purchasePrice">Purchase Price ($)</label>
      <input
        type="text"
        id="purchasePrice"
        name="purchase_price"
        placeholder="{{ stock.purchase_price / 100 }}" />
    </div>

    <div class="field">
      <label for="purchaseDate">Purchase Date</label>
      <input
        type="date"
        id="purchaseDate"
        name="purchase_date"
        value="{{ stock.purchase_date.strftime('%Y-%m-%d') }}" />
    </div>

    <div class="field">
      <button type="submit">Update</button>
    </div>
  </form>
</div>
{% endblock %}

project/stocks/templates/stocks/index.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index_style.css') }}">
{% endblock %}

{% block content %}
<div class="container">
  <header class="content-text">
    <h1>Welcome to the <strong>Flask Stock Portfolio App!</strong></h1>
    <p>Track your personal stock portfolio and view historical stock charts.</p>
  </header>
  <figure class="content-image">
    <img
      src="{{ url_for('static', filename='img/computer_code.jpg') }}"
      alt="Laptop computer on a desk">
  </figure>
</div>
{% endblock %}

project/stocks/templates/stocks/stock_details.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block content %}
<h1>Stock Details</h1>

<h3>Symbol: {{ stock.stock_symbol }}</h3>
<h3>Number of Shares: {{ stock.number_of_shares }}</h3>
<h3>Purchase Price: ${{ stock.purchase_price / 100 }}</h3>
<h3>Purchase Date: {{ stock.purchase_date.strftime("%B %d, %Y") }}</h3>

{% if title != 'Stock chart is unavailable.' %}
  <canvas id="stockChart" width="500" height="400"></canvas>
{% else %}
  <br>
  <h3>{{ title }}</h3>
{% endif %}
{% endblock %}

{% block javascript %}
<script>
// Get the canvas element for modifying the data contents
var ctx = document.getElementById('stockChart').getContext('2d');

// Set the default font color for each chart
Chart.defaults.global.defaultFontColor = 'black';

// Create a new line chart
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels:
      [{% for item in labels %}
         "{{item.strftime("%m/%d/%Y")}}",
      {% endfor %}],
    datasets: [{
      label: 'Share Price ($)',
      data:
        [{% for item in values %}
          {{item}},
        {% endfor %}],
    backgroundColor: 'blue',
    borderColor: 'white',
      borderWidth: 1
    }]
  },
  options: {
    title: {
      display: true,
      text: "{{ title }}"
    },
    legend: {
      display: true,
      position: 'bottom',
      align: 'center'
    },
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        },
      }],
    }
  }
});
</script>
{% endblock %}

project/stocks/templates/stocks/stocks.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
{% endblock %}

{% block content %}
<div class="stock-container">
  <div class="stock-table-heading">
    <h1>Portfolio</h1>
    <a class="add-button" href="{{ url_for('stocks.add_stock') }}">Add Stock</a>
  </div>

  <table class="stock-table">
    <!-- Table Header Row -->
    <thead>
      <tr>
        <th>Stock Symbol</th>
        <th>Number of Shares</th>
        <th>Purchase Price</th>
        <th>Purchase Date</th>
        <th>Current Share Price</th>
        <th>Stock Position Value</th>
        <th>Actions</th>
      </tr>
    </thead>

    <!-- Table Elements (Rows) -->
    <tbody>
      {% for stock in stocks %}
        <tr>
          <td><a href="{{ url_for('stocks.stock_details', id=stock.id) }}">{{ stock.stock_symbol }}</a></td>
          <td>{{ stock.number_of_shares }}</td>
          <td>${{ stock.purchase_price / 100 }}</td>
          <td>{{ stock.purchase_date.strftime("%Y-%m-%d") }}</td>
          <td>${{ stock.current_price / 100 }}</td>
          <td>${{ stock.position_value / 100 }}</td>
          <td class="stock-actions">
            <a class="stocks-actions-link" href="{{ url_for('stocks.delete_stock', id=stock.id) }}">Delete</a>
            <a class="stocks-actions-link" href="{{ url_for('stocks.edit_stock', id=stock.id) }}">Edit</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>

    <!-- Footer Row -->
    <tfoot>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><b>TOTAL VALUE</b></td>
        <td><b>${{ value }}</b></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>
{% endblock %}